---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    git_commit: abc123
    kubernetes.io/ingress.allow-http: "false"
  labels:
    app: droke-gke-test
  name: drone-gke-test-ingress
  namespace: drone-gke-test
spec:
  backend:
    serviceName: drone-gke-test
    servicePort: svc-https
---
apiVersion: v1
data:
  POSTGRESQL_PW: <REDACTED>
  POSTGRESQL_USER: <REDACTED>
kind: Secret
metadata:
  annotations:
    git_commit: abc123
  labels:
    app: drone-gke-test
  name: postgresql-credentials
  namespace: drone-gke-test
type: Opaque
---
apiVersion: v1
data:
  svc_account.json: <REDACTED>
kind: Secret
metadata:
  annotations:
    git_commit: abc123
  labels:
    app: drone-gke-test
  name: gcp-service-account-keys
  namespace: drone-gke-test
type: Opaque
